classdef CalendarMergeMode < macrobond.JSONEnum
% CalendarMergeMode   0 = FullCalendar (Include the full range implied by the frequency and weekday settings)  1 = AvailableInAll (Use points in time that are available in all calendars)  2 = AvailableInAny (Use points in time that are available in any calendar)

    % This file is automatically generated using OpenAPI
    % Specification version: v1
    % MATLAB Generator for OpenAPI version: 1.0.0
    

    properties  (Constant)
        baseType = "int32"
    end

    enumeration 
        FullCalendar (int32(0))
        AvailableInAll (int32(1))
        AvailableInAny (int32(2))
    end

end %class

