classdef SeriesTreeNodeLeaf < macrobond.JSONMapper
% SeriesTreeNodeLeaf Information about a leaf in the series database tree
% 
% SeriesTreeNodeLeaf Properties:
%   nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
%   title - The title of the tree node - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
        nodeType string { macrobond.JSONMapper.fieldName(nodeType,"nodeType") }
        % title - The title of the tree node - type: string
        title string { macrobond.JSONMapper.fieldName(title,"title") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeNodeLeaf(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeNodeLeaf
            end
            obj@macrobond.JSONMapper(s,inputs);
        end
    end %methods
end %class

