classdef SeriesTreeNodeBranch < macrobond.JSONMapper
% SeriesTreeNodeBranch Information about a branch in the series database tree
% 
% SeriesTreeNodeBranch Properties:
%   nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
%   title - The title of the tree node - type: string
%   children - The children of this branch - type: array of SeriesTreeNodeBranch_allOf_children

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
        nodeType string { macrobond.JSONMapper.fieldName(nodeType,"nodeType") }
        % title - The title of the tree node - type: string
        title string { macrobond.JSONMapper.fieldName(title,"title") }
        % children - The children of this branch - type: array of SeriesTreeNodeBranch_allOf_children
        children macrobond.models.SeriesTreeNodeBranch_allOf_children { macrobond.JSONMapper.fieldName(children,"children"), macrobond.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeNodeBranch(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeNodeBranch
            end
            obj@macrobond.JSONMapper(s,inputs);
        end
    end %methods
end %class

