classdef UnifiedSeriesRequest < macrobond.JSONMapper
% UnifiedSeriesRequest Request of a list of series converted to the same calendar
% 
% UnifiedSeriesRequest Properties:
%   frequency - The frequency to convert all series to. The default is to convert to the highest frequency of the series in the request.  1 = Annual (Once a year)  2 = SemiAnnual (One in half a year)  3 = QuadMonthly  4 = Quarterly (Once a quarter)  5 = BiMonthly (Once every 2 months)  6 = Monthly (Once a month)  7 = Weekly (Once a week)  8 = Daily (Once a day)  100 = Lowest (The lowest frequency)  101 = Highest (The highest frequency) - type: SeriesFrequency
%   weekdays - The days of the week used for daily series. The default is Monday to Friday.  1 = Sunday (Represents a Sunday)  2 = Monday (Represents a Monday)  4 = Tuesday (Represents a Tuesday)  8 = Wednesday (Represents a Wednesday)  16 = Thursday (Represents a Thursday)  31 = SundayToThursday (Sunday to Thursday daymask, weekend on Friday and Saturday)  32 = Friday (Represents a Friday)  62 = MondayToFriday (Standard five day week)  64 = Saturday (Represents a Saturday)  79 = SaturdayToWednesday (Saturday to Wednesday daymask, weekend on Thursday and Friday)  94 = MondayToThursdayAndSaturday (Monday to Thursday and Saturday, weekend on Friday and Sunday)  95 = SaturdayToThursday (Saturday to Thursday, weekend on Friday)  127 = FullWeek (All days of the week) - type: SeriesWeekdays
%   calendarMergeMode - The merge mode determines how the series calendars are used when forming the new shared calendar. The default is to use all observations that are in any calendar.  0 = FullCalendar (Include the full range implied by the frequency and weekday settings)  1 = AvailableInAll (Use points in time that are available in all calendars)  2 = AvailableInAny (Use points in time that are available in any calendar) - type: CalendarMergeMode
%   currency - The currency to use for currency conversion or omitted for no conversion. - type: string
%   startDateMode - The start date mode determines how the start date is calculated. By default the mode is to start when there is data in any series.  0 = DataInAnySeries (All the series start or end when there is data in any series)  1 = DataInAllSeries (All the series start or end when there is data in all series) - type: CalendarDateMode
%   startPoint - The start point. By default, this is determined by the startDateMode. It can be a date on the format yyyy-mm-dd or a number of observations relative the end of the series. - type: string
%   endDateMode - The end date mode determines how the end date is calculated. By default the mode is to end when there is no data in any series.  0 = DataInAnySeries (All the series start or end when there is data in any series)  1 = DataInAllSeries (All the series start or end when there is data in all series) - type: CalendarDateMode
%   endPoint - The end point. By default, this is determined by the endDateMode. It can be a date on the format yyyy-mm-dd or a number of observations relative the end of the series. - type: string
%   seriesEntries - The list of series entries that defines the series to request. - type: array of UnifiedSeriesEntry

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % frequency - The frequency to convert all series to. The default is to convert to the highest frequency of the series in the request.  1 = Annual (Once a year)  2 = SemiAnnual (One in half a year)  3 = QuadMonthly  4 = Quarterly (Once a quarter)  5 = BiMonthly (Once every 2 months)  6 = Monthly (Once a month)  7 = Weekly (Once a week)  8 = Daily (Once a day)  100 = Lowest (The lowest frequency)  101 = Highest (The highest frequency) - type: SeriesFrequency
        frequency  { macrobond.JSONMapper.fieldName(frequency,"frequency") }
        % weekdays - The days of the week used for daily series. The default is Monday to Friday.  1 = Sunday (Represents a Sunday)  2 = Monday (Represents a Monday)  4 = Tuesday (Represents a Tuesday)  8 = Wednesday (Represents a Wednesday)  16 = Thursday (Represents a Thursday)  31 = SundayToThursday (Sunday to Thursday daymask, weekend on Friday and Saturday)  32 = Friday (Represents a Friday)  62 = MondayToFriday (Standard five day week)  64 = Saturday (Represents a Saturday)  79 = SaturdayToWednesday (Saturday to Wednesday daymask, weekend on Thursday and Friday)  94 = MondayToThursdayAndSaturday (Monday to Thursday and Saturday, weekend on Friday and Sunday)  95 = SaturdayToThursday (Saturday to Thursday, weekend on Friday)  127 = FullWeek (All days of the week) - type: SeriesWeekdays
        weekdays  { macrobond.JSONMapper.fieldName(weekdays,"weekdays") }
        % calendarMergeMode - The merge mode determines how the series calendars are used when forming the new shared calendar. The default is to use all observations that are in any calendar.  0 = FullCalendar (Include the full range implied by the frequency and weekday settings)  1 = AvailableInAll (Use points in time that are available in all calendars)  2 = AvailableInAny (Use points in time that are available in any calendar) - type: CalendarMergeMode
        calendarMergeMode  { macrobond.JSONMapper.fieldName(calendarMergeMode,"calendarMergeMode") }
        % currency - The currency to use for currency conversion or omitted for no conversion. - type: string
        currency string { macrobond.JSONMapper.fieldName(currency,"currency") }
        % startDateMode - The start date mode determines how the start date is calculated. By default the mode is to start when there is data in any series.  0 = DataInAnySeries (All the series start or end when there is data in any series)  1 = DataInAllSeries (All the series start or end when there is data in all series) - type: CalendarDateMode
        startDateMode  { macrobond.JSONMapper.fieldName(startDateMode,"startDateMode") }
        % startPoint - The start point. By default, this is determined by the startDateMode. It can be a date on the format yyyy-mm-dd or a number of observations relative the end of the series. - type: string
        startPoint string { macrobond.JSONMapper.fieldName(startPoint,"startPoint") }
        % endDateMode - The end date mode determines how the end date is calculated. By default the mode is to end when there is no data in any series.  0 = DataInAnySeries (All the series start or end when there is data in any series)  1 = DataInAllSeries (All the series start or end when there is data in all series) - type: CalendarDateMode
        endDateMode  { macrobond.JSONMapper.fieldName(endDateMode,"endDateMode") }
        % endPoint - The end point. By default, this is determined by the endDateMode. It can be a date on the format yyyy-mm-dd or a number of observations relative the end of the series. - type: string
        endPoint string { macrobond.JSONMapper.fieldName(endPoint,"endPoint") }
        % seriesEntries - The list of series entries that defines the series to request. - type: array of UnifiedSeriesEntry
        seriesEntries macrobond.models.UnifiedSeriesEntry { macrobond.JSONMapper.fieldName(seriesEntries,"seriesEntries"), macrobond.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = UnifiedSeriesRequest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.UnifiedSeriesRequest
            end
            obj@macrobond.JSONMapper(s,inputs);
        end
    end %methods
end %class

