classdef AttributeFilterCollection < macrobond.JSONMapper
% AttributeFilterCollection No description provided
% 
% AttributeFilterCollection Properties:
%   filters - The list of suggested filters - type: array of AttributeFilter
%   count - The count of entities covered by the filters - type: int32

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % filters - The list of suggested filters - type: array of AttributeFilter
        filters macrobond.models.AttributeFilter { macrobond.JSONMapper.fieldName(filters,"filters"), macrobond.JSONMapper.JSONArray}
        % count - The count of entities covered by the filters - type: int32
        count int32 { macrobond.JSONMapper.fieldName(count,"count")}
    end

    % Class methods
    methods
        % Constructor
        function obj = AttributeFilterCollection(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.AttributeFilterCollection
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

