classdef AttributeFilterValue < macrobond.JSONMapper
% AttributeFilterValue No description provided
% 
% AttributeFilterValue Properties:
%   value - The value of the attribute for this filter - type: string
%   description - The description of the value - type: string
%   count - The count of entities that has this value - type: int32

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % value - The value of the attribute for this filter - type: string
        value string { macrobond.JSONMapper.fieldName(value,"value")}
        % description - The description of the value - type: string
        description string { macrobond.JSONMapper.fieldName(description,"description")}
        % count - The count of entities that has this value - type: int32
        count int32 { macrobond.JSONMapper.fieldName(count,"count")}
    end

    % Class methods
    methods
        % Constructor
        function obj = AttributeFilterValue(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.AttributeFilterValue
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

