classdef EntityInfoForDisplayGroup < macrobond.JSONMapper
% EntityInfoForDisplayGroup No description provided
% 
% EntityInfoForDisplayGroup Properties:
%   description - Heading of the group - type: string
%   title - Title of the group - type: string
%   items - List of information items - type: array of EntityInfoForDisplayItem

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % description - Heading of the group - type: string
        description string { macrobond.JSONMapper.fieldName(description,"description")}
        % title - Title of the group - type: string
        title string { macrobond.JSONMapper.fieldName(title,"title")}
        % items - List of information items - type: array of EntityInfoForDisplayItem
        items macrobond.models.EntityInfoForDisplayItem { macrobond.JSONMapper.fieldName(items,"items"), macrobond.JSONMapper.JSONArray}
    end

    % Class methods
    methods
        % Constructor
        function obj = EntityInfoForDisplayGroup(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.EntityInfoForDisplayGroup
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

