classdef EntityNameWithTimeStamp < macrobond.JSONMapper
% EntityNameWithTimeStamp Name and timestamp of an entity
% 
% EntityNameWithTimeStamp Properties:
%   name - The entity name - type: string
%   modified - Timestamp when this entity was last modified - type: datetime

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % name - The entity name - type: string
        name string { macrobond.JSONMapper.fieldName(name,"name")}
        % modified - Timestamp when this entity was last modified - type: datetime
        modified datetime { macrobond.JSONMapper.stringDatetime(modified,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), macrobond.JSONMapper.fieldName(modified,"modified")}
    end

    % Class methods
    methods
        % Constructor
        function obj = EntityNameWithTimeStamp(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.EntityNameWithTimeStamp
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

