classdef MetadataValueInformationResponse < macrobond.JSONMapper
% MetadataValueInformationResponse Information about a metadata value
% 
% MetadataValueInformationResponse Properties:
%   attributeName - The name of the metadata attribute - type: string
%   value - type: MetadataValueInformationResponse_value
%   description - The description of the metadata value - type: string
%   comment - The comment of the metadata value - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % attributeName - The name of the metadata attribute - type: string
        attributeName string { macrobond.JSONMapper.fieldName(attributeName,"attributeName")}
        % value - type: MetadataValueInformationResponse_value
        value  { macrobond.JSONMapper.fieldName(value,"value")}
        % description - The description of the metadata value - type: string
        description string { macrobond.JSONMapper.fieldName(description,"description")}
        % comment - The comment of the metadata value - type: string
        comment string { macrobond.JSONMapper.fieldName(comment,"comment")}
    end

    % Class methods
    methods
        % Constructor
        function obj = MetadataValueInformationResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.MetadataValueInformationResponse
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

