classdef SeriesTreeListingSeries < macrobond.JSONMapper
% SeriesTreeListingSeries Defines an aspect in a structured series list
% 
% SeriesTreeListingSeries Properties:
%   discontinued - If True then the series is discontinued. This is typically indicated by drawing the series title in red. - type: logical
%   indentation - The indentation level. - type: int32
%   emphasized - If True then the series is emphasized. This is typically indicated by drawing the series title in bold. - type: logical
%   spaceAbove - If True then some extra space should be drawn above this series. - type: logical
%   xproperties - Properties that can be used for display purposes. It will always contain a property called Description. If there is a series, the property Name will contain the series name. If there is no Name, the series is missing and the description is typically shown as ''disabled''. - type: macrobond.JSONMapperMap

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % discontinued - If True then the series is discontinued. This is typically indicated by drawing the series title in red. - type: logical
        discontinued logical { macrobond.JSONMapper.fieldName(discontinued,"discontinued")}
        % indentation - The indentation level. - type: int32
        indentation int32 { macrobond.JSONMapper.fieldName(indentation,"indentation")}
        % emphasized - If True then the series is emphasized. This is typically indicated by drawing the series title in bold. - type: logical
        emphasized logical { macrobond.JSONMapper.fieldName(emphasized,"emphasized")}
        % spaceAbove - If True then some extra space should be drawn above this series. - type: logical
        spaceAbove logical { macrobond.JSONMapper.fieldName(spaceAbove,"spaceAbove")}
        % xproperties - Properties that can be used for display purposes. It will always contain a property called Description. If there is a series, the property Name will contain the series name. If there is no Name, the series is missing and the description is typically shown as ''disabled''. - type: macrobond.JSONMapperMap
        xproperties  { macrobond.JSONMapper.fieldName(xproperties,"properties")}
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeListingSeries(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeListingSeries
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

