classdef SeriesTreeListingResponse < macrobond.JSONMapper
% SeriesTreeListingResponse A structured list of series for a leaf in the series database tree
% 
% SeriesTreeListingResponse Properties:
%   commonTitle - The common part of the series titles - type: string
%   hasAspects - If True then there are several aspects of the series which is typically displayed as tabs - type: logical
%   hasGroups - If True then the list is grouped - type: logical
%   aspects - The list of aspects. There will always be at least one. - type: array of SeriesTreeListingAspect

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % commonTitle - The common part of the series titles - type: string
        commonTitle string { macrobond.JSONMapper.fieldName(commonTitle,"commonTitle")}
        % hasAspects - If True then there are several aspects of the series which is typically displayed as tabs - type: logical
        hasAspects logical { macrobond.JSONMapper.fieldName(hasAspects,"hasAspects")}
        % hasGroups - If True then the list is grouped - type: logical
        hasGroups logical { macrobond.JSONMapper.fieldName(hasGroups,"hasGroups")}
        % aspects - The list of aspects. There will always be at least one. - type: array of SeriesTreeListingAspect
        aspects macrobond.models.SeriesTreeListingAspect { macrobond.JSONMapper.fieldName(aspects,"aspects"), macrobond.JSONMapper.JSONArray}
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeListingResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeListingResponse
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

