classdef SeriesTreeNodeBranchRef < macrobond.models.SeriesTreeNodeResponse
% SeriesTreeNodeBranchRef Information about a branch reference in the series database tree
% 
% SeriesTreeNodeBranchRef Properties:
%   path - The path of the sub tree - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % path - The path of the sub tree - type: string
        path string { macrobond.JSONMapper.fieldName(path,"path")}
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeNodeBranchRef(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeNodeBranchRef
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

