classdef SeriesStorageLocationResponse < macrobond.JSONMapper
% SeriesStorageLocationResponse A series storage location
% 
% SeriesStorageLocationResponse Properties:
%   name - The description of the location - type: string
%   seriesPrefix - The series prefix to use for this location - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % name - The description of the location - type: string
        name string { macrobond.JSONMapper.fieldName(name,"name")}
        % seriesPrefix - The series prefix to use for this location - type: string
        seriesPrefix string { macrobond.JSONMapper.fieldName(seriesPrefix,"seriesPrefix")}
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesStorageLocationResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesStorageLocationResponse
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

