classdef SeriesTreeNodeLeaf < macrobond.models.SeriesTreeNodeResponse
% SeriesTreeNodeLeaf Information about a leaf in the series database tree
% 
% SeriesTreeNodeLeaf Properties:

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeNodeLeaf(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeNodeLeaf
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

