classdef UnifiedSeriesResponse < macrobond.JSONMapper
% UnifiedSeriesResponse Response from a unified series request
% 
% UnifiedSeriesResponse Properties:
%   dates - The dates of the series or not specified if there were only errors - type: array of datetime
%   series - The list of series responses in the same order as in the request - type: array of ValuesResponse

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % dates - The dates of the series or not specified if there were only errors - type: array of datetime
        dates datetime { macrobond.JSONMapper.fieldName(dates,"dates"), macrobond.JSONMapper.JSONArray}
        % series - The list of series responses in the same order as in the request - type: array of ValuesResponse
        series macrobond.models.ValuesResponse { macrobond.JSONMapper.fieldName(series,"series"), macrobond.JSONMapper.JSONArray}
    end

    % Class methods
    methods
        % Constructor
        function obj = UnifiedSeriesResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the initialize method from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.UnifiedSeriesResponse
            end
            obj = obj.initialize(s,inputs);
        end
    end %methods
end %class

