classdef SearchForDisplayResponse < macrobond.JSONMapper
% SearchForDisplayResponse Entity search response with metadata displayed for presentation purposes
% 
% SearchForDisplayResponse Properties:
%   isTruncated - If True, the search response is truncated - type: logical
%   results - The matched entites - type: array of macrobond.JSONMapperMap
%   commonTitle - The common part of the title - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % isTruncated - If True, the search response is truncated - type: logical
        isTruncated logical { macrobond.JSONMapper.fieldName(isTruncated,"isTruncated") }
        % results - The matched entites - type: array of macrobond.JSONMapperMap
        results  { macrobond.JSONMapper.fieldName(results,"results"), macrobond.JSONMapper.JSONArray }
        % commonTitle - The common part of the title - type: string
        commonTitle string { macrobond.JSONMapper.fieldName(commonTitle,"commonTitle") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SearchForDisplayResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SearchForDisplayResponse
            end
            obj@macrobond.JSONMapper(s,inputs);
        end
    end %methods
end %class

