classdef CalendarDateMode < macrobond.JSONEnum
% CalendarDateMode   0 = DataInAnySeries (All the series start or end when there is data in any series)  1 = DataInAllSeries (All the series start or end when there is data in all series)

    % This file is automatically generated using OpenAPI
    % Specification version: v1
    % MATLAB Generator for OpenAPI version: 1.0.0
    

    properties  (Constant)
        baseType = "int32"
    end

    enumeration 
        DataInAnySeries (int32(0))
        DataInAllSeries (int32(1))
    end

end %class

