classdef SeriesTreeListingGroup < macrobond.JSONMapper
% SeriesTreeListingGroup Defines an aspect in a structured series list
% 
% SeriesTreeListingGroup Properties:
%   title - The title of the group. This is might be omitted if there is only one group. - type: string
%   series - The list of series in this group. - type: array of SeriesTreeListingSeries

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % title - The title of the group. This is might be omitted if there is only one group. - type: string
        title string { macrobond.JSONMapper.fieldName(title,"title") }
        % series - The list of series in this group. - type: array of SeriesTreeListingSeries
        series macrobond.models.SeriesTreeListingSeries { macrobond.JSONMapper.fieldName(series,"series"), macrobond.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeListingGroup(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeListingGroup
            end
            obj@macrobond.JSONMapper(s,inputs);
        end
    end %methods
end %class

