classdef SeriesTreeLocationPart < macrobond.JSONMapper
% SeriesTreeLocationPart A location in the database tree
% 
% SeriesTreeLocationPart Properties:
%   title - The title of the location element - type: string
%   child - The child of the location part - type: SeriesTreeLocationPart

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % title - The title of the location element - type: string
        title string { macrobond.JSONMapper.fieldName(title,"title") }
        % child - The child of the location part - type: SeriesTreeLocationPart
        child macrobond.models.SeriesTreeLocationPart { macrobond.JSONMapper.fieldName(child,"child") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeLocationPart(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { macrobond.JSONMapper.ConstructorArgument } = []
                inputs.?macrobond.models.SeriesTreeLocationPart
            end
            obj@macrobond.JSONMapper(s,inputs);
        end
    end %methods
end %class

