classdef DataPackageListResponse < MacrobondMATLABAPI.JSONMapper
% DataPackageListResponse List of entities available in a data package
% 
% DataPackageListResponse Properties:
%   timeStampForIfModifiedSince - A timestamp to pass as the ifModifiedSince parameter in the next request to get incremental updates - type: datetime
%   downloadFullListOnOrAfter - Recommended earliest next time to request a full list by omitting timeStampForIfModifiedSince. - type: datetime
%   state - The state of this list.  0 = FullListing (A complete listing of all series. Make another request for full data at some point after timestamp in downloadFullListOnOrAfter.)  1 = UpToDate (The list contains all updates since the specified start date. Wait 15 minutes before making another request where timeStampForIfModifiedSince is used.)  2 = Incomplete (The list might not contain all updates. Wait one minute and then use the timeStampForIfModifiedSince in an a new request.) - type: DataPackageListState
%   entities - A list of entity names and timestamps when they were last modified. - type: array of EntityNameWithTimeStamp

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % timeStampForIfModifiedSince - A timestamp to pass as the ifModifiedSince parameter in the next request to get incremental updates - type: datetime
        timeStampForIfModifiedSince datetime { MacrobondMATLABAPI.JSONMapper.stringDatetime(timeStampForIfModifiedSince,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), MacrobondMATLABAPI.JSONMapper.fieldName(timeStampForIfModifiedSince,"timeStampForIfModifiedSince") }
        % downloadFullListOnOrAfter - Recommended earliest next time to request a full list by omitting timeStampForIfModifiedSince. - type: datetime
        downloadFullListOnOrAfter datetime { MacrobondMATLABAPI.JSONMapper.stringDatetime(downloadFullListOnOrAfter,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), MacrobondMATLABAPI.JSONMapper.fieldName(downloadFullListOnOrAfter,"downloadFullListOnOrAfter") }
        % state - The state of this list.  0 = FullListing (A complete listing of all series. Make another request for full data at some point after timestamp in downloadFullListOnOrAfter.)  1 = UpToDate (The list contains all updates since the specified start date. Wait 15 minutes before making another request where timeStampForIfModifiedSince is used.)  2 = Incomplete (The list might not contain all updates. Wait one minute and then use the timeStampForIfModifiedSince in an a new request.) - type: DataPackageListState
        state  { MacrobondMATLABAPI.JSONMapper.fieldName(state,"state") }
        % entities - A list of entity names and timestamps when they were last modified. - type: array of EntityNameWithTimeStamp
        entities MacrobondMATLABAPI.models.EntityNameWithTimeStamp { MacrobondMATLABAPI.JSONMapper.fieldName(entities,"entities"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = DataPackageListResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.DataPackageListResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

