classdef EntityInfoForDisplayResponse < MacrobondMATLABAPI.JSONMapper
% EntityInfoForDisplayResponse Entity search response with metadata displayed for presentation purposes
% 
% EntityInfoForDisplayResponse Properties:
%   groups - A list of information groups - type: array of EntityInfoForDisplayGroup

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % groups - A list of information groups - type: array of EntityInfoForDisplayGroup
        groups MacrobondMATLABAPI.models.EntityInfoForDisplayGroup { MacrobondMATLABAPI.JSONMapper.fieldName(groups,"groups"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = EntityInfoForDisplayResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.EntityInfoForDisplayResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

