classdef EntityNameWithTimeStamp < MacrobondMATLABAPI.JSONMapper
% EntityNameWithTimeStamp Name and timestamp of an entity
% 
% EntityNameWithTimeStamp Properties:
%   name - The entity name - type: string
%   modified - Timestamp when this entity was last modified - type: datetime

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % name - The entity name - type: string
        name string { MacrobondMATLABAPI.JSONMapper.fieldName(name,"name") }
        % modified - Timestamp when this entity was last modified - type: datetime
        modified datetime { MacrobondMATLABAPI.JSONMapper.stringDatetime(modified,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), MacrobondMATLABAPI.JSONMapper.fieldName(modified,"modified") }
    end

    % Class methods
    methods
        % Constructor
        function obj = EntityNameWithTimeStamp(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.EntityNameWithTimeStamp
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

