classdef EntityInfoForDisplayGroup < MacrobondMATLABAPI.JSONMapper
% EntityInfoForDisplayGroup No description provided
% 
% EntityInfoForDisplayGroup Properties:
%   description - Heading of the group - type: string
%   title - Title of the group - type: string
%   items - List of information items - type: array of EntityInfoForDisplayItem

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % description - Heading of the group - type: string
        description string { MacrobondMATLABAPI.JSONMapper.fieldName(description,"description") }
        % title - Title of the group - type: string
        title string { MacrobondMATLABAPI.JSONMapper.fieldName(title,"title") }
        % items - List of information items - type: array of EntityInfoForDisplayItem
        items MacrobondMATLABAPI.models.EntityInfoForDisplayItem { MacrobondMATLABAPI.JSONMapper.fieldName(items,"items"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = EntityInfoForDisplayGroup(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.EntityInfoForDisplayGroup
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

