classdef ItemListingResponse < MacrobondMATLABAPI.JSONMapper
% ItemListingResponse The response of listing items that can be organized into directories
% 
% ItemListingResponse Properties:
%   title - The title of the directory - type: string
%   directories - The list of sub directories if any. - type: array of ItemListingResponse
%   items - The list of if any. - type: array of ItemInformation

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % title - The title of the directory - type: string
        title string { MacrobondMATLABAPI.JSONMapper.fieldName(title,"title") }
        % directories - The list of sub directories if any. - type: array of ItemListingResponse
        directories MacrobondMATLABAPI.models.ItemListingResponse { MacrobondMATLABAPI.JSONMapper.fieldName(directories,"directories"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % items - The list of if any. - type: array of ItemInformation
        items MacrobondMATLABAPI.models.ItemInformation { MacrobondMATLABAPI.JSONMapper.fieldName(items,"items"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = ItemListingResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.ItemListingResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

