classdef ItemInformation < MacrobondMATLABAPI.JSONMapper
% ItemInformation No description provided
% 
% ItemInformation Properties:
%   title - The title of the item - type: string
%   path - The path of the item - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % title - The title of the item - type: string
        title string { MacrobondMATLABAPI.JSONMapper.fieldName(title,"title") }
        % path - The path of the item - type: string
        path string { MacrobondMATLABAPI.JSONMapper.fieldName(path,"path") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ItemInformation(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.ItemInformation
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

