classdef MetadataAttributeType < MacrobondMATLABAPI.JSONEnum
% MetadataAttributeType   3 = Int (32-bit signed integer)  5 = Double (64-bit IEEE floating point number)  7 = TimeStamp (A time stamp including date, time of day and time zone)  8 = String (A unicode string)  11 = Bool (A boolean value that can be true of false)

    % This file is automatically generated using OpenAPI
    % Specification version: v1
    % MATLAB Generator for OpenAPI version: 1.0.0
    

    properties  (Constant)
        baseType = "int32"
    end

    enumeration 
        Int (int32(3))
        Double (int32(5))
        TimeStamp (int32(7))
        String (int32(8))
        Bool (int32(11))
    end

end %class

