classdef MetadataAttributeInformationResponse < MacrobondMATLABAPI.JSONMapper
% MetadataAttributeInformationResponse Information about a metadata attribute
% 
% MetadataAttributeInformationResponse Properties:
%   name - The name of the metadata attribute - type: string
%   description - The description of the metadata attribute - type: string
%   comment - The comment of the metadata attribute - type: string
%   valueType - The value type of the metadata attribute  3 = Int (32-bit signed integer)  5 = Double (64-bit IEEE floating point number)  7 = TimeStamp (A time stamp including date, time of day and time zone)  8 = String (A unicode string)  11 = Bool (A boolean value that can be true of false) - type: MetadataAttributeType
%   valueRestriction - Restriction on the value type  1 = Url (The string is an URL)  2 = Email (The string is an e-mail address)  3 = Date (Only the date of the TimeStamp is valid)  4 = Positive (The integer or double is >= 0)  5 = Json (The string is encoded as JSON) - type: MetadataAttributeTypeRestriction
%   usesValueList - If True, the metadata attribute uses a list of values - type: logical
%   canListValues - If True then the values of this type of metadata can be listen using the ListAllValues function - type: logical
%   canHaveMultipleValues - If True then this type of metadata can have multiple values in a metadata collection - type: logical
%   isDatabaseEntity - If True then this type of metadata is an entity that can be retrieved from the database - type: logical
%   appliesTo - If provided, specifies what types of entities that this attribute applies to - type: array of string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % name - The name of the metadata attribute - type: string
        name string { MacrobondMATLABAPI.JSONMapper.fieldName(name,"name") }
        % description - The description of the metadata attribute - type: string
        description string { MacrobondMATLABAPI.JSONMapper.fieldName(description,"description") }
        % comment - The comment of the metadata attribute - type: string
        comment string { MacrobondMATLABAPI.JSONMapper.fieldName(comment,"comment") }
        % valueType - The value type of the metadata attribute  3 = Int (32-bit signed integer)  5 = Double (64-bit IEEE floating point number)  7 = TimeStamp (A time stamp including date, time of day and time zone)  8 = String (A unicode string)  11 = Bool (A boolean value that can be true of false) - type: MetadataAttributeType
        valueType  { MacrobondMATLABAPI.JSONMapper.fieldName(valueType,"valueType") }
        % valueRestriction - Restriction on the value type  1 = Url (The string is an URL)  2 = Email (The string is an e-mail address)  3 = Date (Only the date of the TimeStamp is valid)  4 = Positive (The integer or double is >= 0)  5 = Json (The string is encoded as JSON) - type: MetadataAttributeTypeRestriction
        valueRestriction  { MacrobondMATLABAPI.JSONMapper.fieldName(valueRestriction,"valueRestriction") }
        % usesValueList - If True, the metadata attribute uses a list of values - type: logical
        usesValueList logical { MacrobondMATLABAPI.JSONMapper.fieldName(usesValueList,"usesValueList") }
        % canListValues - If True then the values of this type of metadata can be listen using the ListAllValues function - type: logical
        canListValues logical { MacrobondMATLABAPI.JSONMapper.fieldName(canListValues,"canListValues") }
        % canHaveMultipleValues - If True then this type of metadata can have multiple values in a metadata collection - type: logical
        canHaveMultipleValues logical { MacrobondMATLABAPI.JSONMapper.fieldName(canHaveMultipleValues,"canHaveMultipleValues") }
        % isDatabaseEntity - If True then this type of metadata is an entity that can be retrieved from the database - type: logical
        isDatabaseEntity logical { MacrobondMATLABAPI.JSONMapper.fieldName(isDatabaseEntity,"isDatabaseEntity") }
        % appliesTo - If provided, specifies what types of entities that this attribute applies to - type: array of string
        appliesTo string { MacrobondMATLABAPI.JSONMapper.fieldName(appliesTo,"appliesTo"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = MetadataAttributeInformationResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.MetadataAttributeInformationResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

