classdef MetadataValueInformationResponse_value < MacrobondMATLABAPI.JSONMapper
% MetadataValueInformationResponse_value The value
% 
% MetadataValueInformationResponse_value Properties:

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0

    % Class properties
    properties
    end

    % Class methods
    methods
        % Constructor
        function obj = MetadataValueInformationResponse_value(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.MetadataValueInformationResponse_value
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end

        

    end %methods
end %class

