classdef MetadataAttributeTypeRestriction < MacrobondMATLABAPI.JSONEnum
% MetadataAttributeTypeRestriction   1 = Url (The string is an URL)  2 = Email (The string is an e-mail address)  3 = Date (Only the date of the TimeStamp is valid)  4 = Positive (The integer or double is >= 0)  5 = Json (The string is encoded as JSON)

    % This file is automatically generated using OpenAPI
    % Specification version: v1
    % MATLAB Generator for OpenAPI version: 1.0.0
    

    properties  (Constant)
        baseType = "int32"
    end

    enumeration 
        Url (int32(1))
        Email (int32(2))
        Date (int32(3))
        Positive (int32(4))
        Json (int32(5))
    end

end %class

