classdef SearchResponse < MacrobondMATLABAPI.JSONMapper
% SearchResponse Entity search response
% 
% SearchResponse Properties:
%   isTruncated - If True, the search response is truncated - type: logical
%   results - The matched entites - type: array of MacrobondMATLABAPI.JSONMapperMap

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % isTruncated - If True, the search response is truncated - type: logical
        isTruncated logical { MacrobondMATLABAPI.JSONMapper.fieldName(isTruncated,"isTruncated") }
        % results - The matched entites - type: array of MacrobondMATLABAPI.JSONMapperMap
        results  { MacrobondMATLABAPI.JSONMapper.fieldName(results,"results"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = SearchResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SearchResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

