classdef SearchFilter < MacrobondMATLABAPI.JSONMapper
% SearchFilter A filter in a search request
% 
% SearchFilter Properties:
%   entityTypes - One or more entity types to include in the search. An empty list will include all types. If not specified, the search will be made for TimeSeries. - type: array of string
%   mustHaveValues - Pairs of attributes and values to be matched against entities when searching - type: MacrobondMATLABAPI.JSONMapperMap
%   mustNotHaveValues - Pairs of attributes and values to exclude entities when searching - type: MacrobondMATLABAPI.JSONMapperMap
%   mustHaveAttributes - Attributes to be matched against entities when searching. Any value will match. - type: array of string
%   mustNotHaveAttributes - Attributes to exclude entities when searching. Any value will match. - type: array of string
%   text - Words to search for separated by space. - type: string
%   mustHaveFilterListPath - Optional path to filter list that is added to the set of MustHaveValues. The paths are typically obtained from a call ListFilterLists. - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % entityTypes - One or more entity types to include in the search. An empty list will include all types. If not specified, the search will be made for TimeSeries. - type: array of string
        entityTypes string { MacrobondMATLABAPI.JSONMapper.fieldName(entityTypes,"entityTypes"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % mustHaveValues - Pairs of attributes and values to be matched against entities when searching - type: MacrobondMATLABAPI.JSONMapperMap
        mustHaveValues  { MacrobondMATLABAPI.JSONMapper.fieldName(mustHaveValues,"mustHaveValues") }
        % mustNotHaveValues - Pairs of attributes and values to exclude entities when searching - type: MacrobondMATLABAPI.JSONMapperMap
        mustNotHaveValues  { MacrobondMATLABAPI.JSONMapper.fieldName(mustNotHaveValues,"mustNotHaveValues") }
        % mustHaveAttributes - Attributes to be matched against entities when searching. Any value will match. - type: array of string
        mustHaveAttributes string { MacrobondMATLABAPI.JSONMapper.fieldName(mustHaveAttributes,"mustHaveAttributes"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % mustNotHaveAttributes - Attributes to exclude entities when searching. Any value will match. - type: array of string
        mustNotHaveAttributes string { MacrobondMATLABAPI.JSONMapper.fieldName(mustNotHaveAttributes,"mustNotHaveAttributes"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % text - Words to search for separated by space. - type: string
        text string { MacrobondMATLABAPI.JSONMapper.fieldName(text,"text") }
        % mustHaveFilterListPath - Optional path to filter list that is added to the set of MustHaveValues. The paths are typically obtained from a call ListFilterLists. - type: string
        mustHaveFilterListPath string { MacrobondMATLABAPI.JSONMapper.fieldName(mustHaveFilterListPath,"mustHaveFilterListPath") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SearchFilter(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SearchFilter
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

