classdef SeriesTreeNodeBranchRef < MacrobondMATLABAPI.JSONMapper
% SeriesTreeNodeBranchRef Information about a branch reference in the series database tree
% 
% SeriesTreeNodeBranchRef Properties:
%   nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
%   title - The title of the tree node - type: string
%   path - The path of the sub tree - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
        nodeType string { MacrobondMATLABAPI.JSONMapper.fieldName(nodeType,"nodeType") }
        % title - The title of the tree node - type: string
        title string { MacrobondMATLABAPI.JSONMapper.fieldName(title,"title") }
        % path - The path of the sub tree - type: string
        path string { MacrobondMATLABAPI.JSONMapper.fieldName(path,"path") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeNodeBranchRef(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SeriesTreeNodeBranchRef
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

