classdef SeriesRequest < MacrobondMATLABAPI.JSONMapper
% SeriesRequest A time series request
% 
% SeriesRequest Properties:
%   values - The values of the series. - type: array of double
%   dates - The dates of the series or not specified if deducted from metadata. When included, it must be the same length as the list of Values. - type: array of datetime
%   forecastFlags - An optional array of forecast flags. When included, it must be the same length as the list of Values. - type: array of logical
%   metadata - The metadata. - type: MacrobondMATLABAPI.JSONMapperMap
%   metadataBaseSeries - An optional existing series to inherit metadata from. - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % values - The values of the series. - type: array of double
        values double { MacrobondMATLABAPI.JSONMapper.fieldName(values,"values"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % dates - The dates of the series or not specified if deducted from metadata. When included, it must be the same length as the list of Values. - type: array of datetime
        dates datetime { MacrobondMATLABAPI.JSONMapper.fieldName(dates,"dates"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % forecastFlags - An optional array of forecast flags. When included, it must be the same length as the list of Values. - type: array of logical
        forecastFlags logical { MacrobondMATLABAPI.JSONMapper.fieldName(forecastFlags,"forecastFlags"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % metadata - The metadata. - type: MacrobondMATLABAPI.JSONMapperMap
        metadata  { MacrobondMATLABAPI.JSONMapper.fieldName(metadata,"metadata") }
        % metadataBaseSeries - An optional existing series to inherit metadata from. - type: string
        metadataBaseSeries string { MacrobondMATLABAPI.JSONMapper.fieldName(metadataBaseSeries,"metadataBaseSeries") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesRequest(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SeriesRequest
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

