classdef SeriesObservationHistoryResponse < MacrobondMATLABAPI.JSONMapper
% SeriesObservationHistoryResponse The history of changes of an observation
% 
% SeriesObservationHistoryResponse Properties:
%   observationDate - The date of the observation - type: datetime
%   values - The historical values of the observation or an empty list if there are no recorded values for the specified date. - type: array of double
%   timeStamps - A list of timestamps of when the historical values were recorded. The first timestamp may be null if the time of the original is unknown. - type: array of datetime

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % observationDate - The date of the observation - type: datetime
        observationDate datetime { MacrobondMATLABAPI.JSONMapper.fieldName(observationDate,"observationDate") }
        % values - The historical values of the observation or an empty list if there are no recorded values for the specified date. - type: array of double
        values double { MacrobondMATLABAPI.JSONMapper.fieldName(values,"values"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % timeStamps - A list of timestamps of when the historical values were recorded. The first timestamp may be null if the time of the original is unknown. - type: array of datetime
        timeStamps datetime { MacrobondMATLABAPI.JSONMapper.fieldName(timeStamps,"timeStamps"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesObservationHistoryResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SeriesObservationHistoryResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

