classdef SeriesTreeListingResponse < MacrobondMATLABAPI.JSONMapper
% SeriesTreeListingResponse A structured list of series for a leaf in the series database tree
% 
% SeriesTreeListingResponse Properties:
%   commonTitle - The common part of the series titles - type: string
%   hasAspects - If True then there are several aspects of the series which is typically displayed as tabs - type: logical
%   hasGroups - If True then the list is grouped - type: logical
%   aspects - The list of aspects. There will always be at least one. - type: array of SeriesTreeListingAspect

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % commonTitle - The common part of the series titles - type: string
        commonTitle string { MacrobondMATLABAPI.JSONMapper.fieldName(commonTitle,"commonTitle") }
        % hasAspects - If True then there are several aspects of the series which is typically displayed as tabs - type: logical
        hasAspects logical { MacrobondMATLABAPI.JSONMapper.fieldName(hasAspects,"hasAspects") }
        % hasGroups - If True then the list is grouped - type: logical
        hasGroups logical { MacrobondMATLABAPI.JSONMapper.fieldName(hasGroups,"hasGroups") }
        % aspects - The list of aspects. There will always be at least one. - type: array of SeriesTreeListingAspect
        aspects MacrobondMATLABAPI.models.SeriesTreeListingAspect { MacrobondMATLABAPI.JSONMapper.fieldName(aspects,"aspects"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeListingResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SeriesTreeListingResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

