classdef SeriesTreeNodeBranch_allOf_children < MacrobondMATLABAPI.JSONMapper
% SeriesTreeNodeBranch_allOf_children Information about a node in the series database tree
% 
% SeriesTreeNodeBranch_allOf_children Properties:
%   nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
%   title - The title of the tree node - type: string
%   children - The children of this branch - type: array of SeriesTreeNodeBranch_allOf_children
%   path - The path of the sub tree - type: string

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0

    % Class properties
    properties
        % nodeType - The node type. Can be one of ''leaf'', ''branch'', ''branchref''. - type: string
        nodeType string { MacrobondMATLABAPI.JSONMapper.fieldName(nodeType,"nodeType") }
        % title - The title of the tree node - type: string
        title string { MacrobondMATLABAPI.JSONMapper.fieldName(title,"title") }
        % children - The children of this branch - type: array of SeriesTreeNodeBranch_allOf_children
        children MacrobondMATLABAPI.models.SeriesTreeNodeBranch_allOf_children { MacrobondMATLABAPI.JSONMapper.fieldName(children,"children"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % path - The path of the sub tree - type: string
        path string { MacrobondMATLABAPI.JSONMapper.fieldName(path,"path") }
    end

    % Class methods
    methods
        % Constructor
        function obj = SeriesTreeNodeBranch_allOf_children(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.SeriesTreeNodeBranch_allOf_children
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end

        function out = getSpecificClass(obj)
            % Create an instance of the more specific class
            switch (obj.nodeType)
                case "branch"
                    out = MacrobondMATLABAPI.models.SeriesTreeNodeBranch();
                case "branchref"
                    out = MacrobondMATLABAPI.models.SeriesTreeNodeBranchRef();
                case "leaf"
                    out = MacrobondMATLABAPI.models.SeriesTreeNodeLeaf();
                case "SeriesTreeNodeBranch"
                    out = MacrobondMATLABAPI.models.SeriesTreeNodeBranch();
                case "SeriesTreeNodeBranchRef"
                    out = MacrobondMATLABAPI.models.SeriesTreeNodeBranchRef();
                case "SeriesTreeNodeLeaf"
                    out = MacrobondMATLABAPI.models.SeriesTreeNodeLeaf();
            end
            % Copy only the relevant property values
            for p = string(properties(out))'
                out.(p) = obj.(p);
            end
        end

    end %methods
end %class

