classdef SeriesFrequency < MacrobondMATLABAPI.JSONEnum
% SeriesFrequency   1 = Annual (Once a year)  2 = SemiAnnual (One in half a year)  3 = QuadMonthly  4 = Quarterly (Once a quarter)  5 = BiMonthly (Once every 2 months)  6 = Monthly (Once a month)  7 = Weekly (Once a week)  8 = Daily (Once a day)  100 = Lowest (The lowest frequency)  101 = Highest (The highest frequency)

    % This file is automatically generated using OpenAPI
    % Specification version: v1
    % MATLAB Generator for OpenAPI version: 1.0.0
    

    properties  (Constant)
        baseType = "int32"
    end

    enumeration 
        Annual (int32(1))
        SemiAnnual (int32(2))
        QuadMonthly (int32(3))
        Quarterly (int32(4))
        BiMonthly (int32(5))
        Monthly (int32(6))
        Weekly (int32(7))
        Daily (int32(8))
        Lowest (int32(100))
        Highest (int32(101))
    end

end %class

