classdef UnifiedSeriesResponse < MacrobondMATLABAPI.JSONMapper
% UnifiedSeriesResponse Response from a unified series request
% 
% UnifiedSeriesResponse Properties:
%   dates - The dates of the series or not specified if there were only errors - type: array of datetime
%   series - The list of series responses in the same order as in the request - type: array of ValuesResponse

% This file is automatically generated using OpenAPI
% Specification version: v1
% MATLAB Generator for OpenAPI version: 1.0.0


    % Class properties
    properties
        % dates - The dates of the series or not specified if there were only errors - type: array of datetime
        dates datetime { MacrobondMATLABAPI.JSONMapper.fieldName(dates,"dates"), MacrobondMATLABAPI.JSONMapper.JSONArray }
        % series - The list of series responses in the same order as in the request - type: array of ValuesResponse
        series MacrobondMATLABAPI.models.ValuesResponse { MacrobondMATLABAPI.JSONMapper.fieldName(series,"series"), MacrobondMATLABAPI.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = UnifiedSeriesResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { MacrobondMATLABAPI.JSONMapper.ConstructorArgument } = []
                inputs.?MacrobondMATLABAPI.models.UnifiedSeriesResponse
            end
            obj@MacrobondMATLABAPI.JSONMapper(s,inputs);
        end
    end %methods
end %class

